# ruff.toml

line-length = 100
target-version = "py312"
extend-exclude = [
    "data",
    "dependencies",
    "experiments_output",
]

[lint]
# select = [
#     "E",    # pycodestyle errors
#     "F",    # pyflakes
#     "I",    # isorti
#     "I001", # Enforce import sorting
#     "B",    # flake8-bugbear
#     "C",    # flake8-comprehensions
#     "UP",   # pyupgrade
#     "D203", # Require blank line before class
#     "D100", # Require docstring for public modules
#     "D101", # Require docstring for public classes
#     "D102", # Require docstring for public methods
#     "D103", # Require docstring for public functions
#     "D104", # Require docstring for public packages
#     "D105", # Require docstring for magic methods
#     "D213", # Multi-line docstring summary should start at the second line
#     # D212 and D213 are mutually exclusive; choose one style only.
# ]

select = ["ALL"]
ignore = [
    "D107", # Allow missing docstring in __init__ if class docstring is present,
    "D212", # Disable first-line summary style in favor of D213 second-line style
    "Q000", # Allow double quotes,
    "D100", # Allow missing docstring in public modules
    "INP001", # Allow implicit namespace packages
    "COM812", # Skip the check for trailing commas in function calls
    "D101", # Allow missing docstring in public classes
    "RET504", # Allow unnecessary assignment of variables in return statements. It is useful for readability in AI code.
    "PLR0913", # Allow too many arguments in functions. It is useful for readability in AI code.
]

[lint.pydocstyle]
# Keep docstrings aligned with Google-style documentation.
convention = "google"

[lint.per-file-ignores]
"src/rbspaper/pipeline/core.py" = ["C901", "PLR0912"]
"__init__.py" = ["F401"]
"notebooks/**/*.ipynb" = ["D", "E402", "T201"]
"test/*.py" = ["D", "E501", "PLR2004", "S101", "N812", "ANN001", "ANN003", "ANN202", "RUF059", "ERA001", "PLC0415", "SLF001", "I001", "B017", "PT011", "ARG001", "NPY002", "F401", "S108", "ANN401", "ARG002", "ARG005"]
"test/**/*.py" = ["D", "E501", "PLR2004", "S101", "N812", "ANN001", "ANN003", "ANN202", "RUF059", "ERA001", "PLC0415", "SLF001", "I001", "B017", "PT011", "ARG001", "NPY002", "F401", "S108", "ANN401", "ARG002", "ARG005"]
"runners/py/*.py" = ["T201", "EXE001", "BLE001", "C901"]
"src/rbspaper/adapters/*.py" = ["ANN401", "TC001"]

[lint.isort]
# Combine "as" imports into a single line
combine-as-imports = true
# Ensure imports are sorted within sections
force-sort-within-sections = true
# Do not order imports by type
order-by-type = false

[format]
# Use single quotes for strings
quote-style = "single"
# Use spaces for indentation
indent-style = "space"
# Avoid adding trailing commas unnecessarily
skip-magic-trailing-comma = true
# Use the system's default line endings
line-ending = "auto"